---
name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

defaults:
  run:
    shell: bash

env:
  python-version: "3.10"

jobs:
  test-lib:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: test and package python
        run: |
          set -exuo pipefail
          python -m venv venv
          . venv/bin/activate
          pushd src/lib
          python -m pip install -r requirements.txt -r requirements-dev.txt
          python -m pytest SmiServices/*.py